{
 "title": "Docker",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_total_bytes",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_limit_bytes",
     "legendFormat": "__auto"
    },
    { "expr": "container_memory_percent_ratio", "legendFormat": "__auto" },
    {
     "expr": "rate(container_network_io_usage_rx_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_io_usage_tx_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_blockio_io_service_bytes_recursive_total{operation=\"read\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_blockio_io_service_bytes_recursive_total{operation=\"write\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    { "expr": "container_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_nanoseconds_total[$__rate_interval])/1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_total_bytes",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Net Rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_io_usage_rx_bytes_total[$__rate_interval])",
     "legendFormat": "{{container_name}} Net Rx"
    }
   ]
  },
  {
   "title": "Net Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(container_network_io_usage_tx_bytes_total[$__rate_interval])",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}